// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const migrationDatabaseUrl =
  process.env["DIRECT_URL"] ??
  process.env["DIRECT_DATABASE_URL"] ??
  process.env["DATABASE_URL"];

if (!migrationDatabaseUrl) {
  throw new Error("DIRECT_URL, DIRECT_DATABASE_URL, or DATABASE_URL is required for Prisma CLI commands");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: migrationDatabaseUrl,
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"] || undefined,
  },
});
